#library "XtraSpheresACS"
#include "zcommon.acs"

script "ExtraSpheresACS" (void)
{
SetResultValue(GetCVar("ExtraSpheres_CVar"));
}

script "InfraredNewRandomACS" (void)
{
SetResultValue(GetCVar("Crucifix_Spawner_CVar"));
}

script "AllMapNewRandomACS" (void)
{
SetResultValue(GetCVar("MapRadar_Spawner_CVar"));
}

script "RadsuitNewRandomACS" (void)
{
SetResultValue(GetCVar("Biosuit_Spawner_CVar"));
}

script "BlueArmorsNewRandomACS" (void)
{
SetResultValue(GetCVar("RedArmor_Spawner_CVar"));
}